# Generated by Django 4.2.1 on 2023-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0003_alter_activeemail_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeemail",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
