# Generated by Django 4.2.1 on 2023-05-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0005_inbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="SendActiveEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
        ),
    ]
